# _config.yml
title: "Boho Byte Bags"
description: "Handmade threads for wired minds"
url: "https://bohobytebags.com"
baseurl: ""  # Important: leave blank for custom domain

remote_theme: "tedivm/jekyll-theme-portfolio"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: /assets/css/style.css
